### ISSUE TITLE
Open-source as a gem

### ISSUE THREAD

**Issue by kanevk** [tradeo/clevertap-ruby#4]
Currently, there isn't other "CleverTap" Ruby client. It can be useful as an advertisement.

**Comment by joshkurien** [comment]
Could one of the owners publish this as a gem in [Ruby gems](https://rubygems.org/)

**Comment by betasve** [comment]
@joshkurien We've just published the gem. Please, let us know if you run into any troubles installing or using the gem. Have a happy coding :) 
https://rubygems.org/gems/clever_tap
